import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner"

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans", 
  weight: ["400", "700"], 
});

export const metadata: Metadata = {
  title: "Temu Dataku Mini Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased flex flex-col items-center justify-center`}
      >
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
